### ISSUE TITLE
Change max page width

### ISSUE THREAD

**Issue by justingit** [movabletype/mt-theme-rainier#3]
Is there an easy way to customize the theme to allow a larger max page width than 930px?

**Comment by yuji** [comment]
Hi,

I'm not sure this is easy way or not, but you can edit "930px" that contains in mt-static/support/theme_static/rainier/css/base.css directory. Or override by new style sheet in your blog/website.
Currently, Rainier  has no way to customize by any theme's parameter.

**Comment by charsbar** [comment]
Closing.
